backend:
  name: git-gateway

media_folder: "site/static/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "program_pages"
    label: "Program Pages"
    folder: "site/content/programs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Slug, name: slug, widget: string }
      - { label: Hero Image, name: hero, widget: image, required: false }
      - { label: Intro, name: intro, widget: text }
      - { label: Program Highlights, name: highlights, widget: list, field: {label: Item, name: item, widget: string} }
      - { label: Who Should Apply, name: who, widget: text }
      - { label: How to Apply (Steps), name: steps, widget: list, field: {label: Step, name: step, widget: string} }
      - { label: Contact (Markdown), name: contact, widget: markdown }
